// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCINzVK_9PRKpxNGATla5gGVNVVLEOjEEA',
    appId: '1:654285631870:web:34563717345898bf72832f',
    messagingSenderId: '654285631870',
    projectId: 'cart-pos-personal',
    authDomain: 'cart-pos-personal.firebaseapp.com',
    storageBucket: 'cart-pos-personal.firebasestorage.app',
    measurementId: 'G-K1ZH34P0RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCitg-aMm2WE-tROCvxpmOQ2-ZWEEOsGcg',
    appId: '1:654285631870:android:f7512d5808a5a8ee72832f',
    messagingSenderId: '654285631870',
    projectId: 'cart-pos-personal',
    storageBucket: 'cart-pos-personal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHZoQ5fOb6VeM9wIYErky9PKPJRRa7ecM',
    appId: '1:654285631870:ios:bf73e19bb0d81b7072832f',
    messagingSenderId: '654285631870',
    projectId: 'cart-pos-personal',
    storageBucket: 'cart-pos-personal.firebasestorage.app',
    iosBundleId: 'com.griller.zone.listMaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHZoQ5fOb6VeM9wIYErky9PKPJRRa7ecM',
    appId: '1:654285631870:ios:bf73e19bb0d81b7072832f',
    messagingSenderId: '654285631870',
    projectId: 'cart-pos-personal',
    storageBucket: 'cart-pos-personal.firebasestorage.app',
    iosBundleId: 'com.griller.zone.listMaker',
  );
}
